[project]
name = "ssg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Andy Babcock", email = "andybabcock@jtof.dev" }]
requires-python = ">=3.14"
dependencies = ["djlint>=1.45.2", "jinja2>=3.1.6", "livereload>=2.7.1"]

[project.scripts]
ssg = "ssg:main"
# ssg = "ssg.cli:main"
liveserver = "ssg.live_server:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.djlint]
indent = 2
