query TournamentQuery($slug: String, $slug_event: String) {
  tournament(slug: $slug) {
    name
    startAt
    endAt
    city
    addrState
    venueAddress
    timezone
    images {
      url
      width
    }
  }
  event(slug: $slug_event) {
    id
  }
}